In [1]:
from math import sqrt
import math as m
import numpy as np
from sklearn import datasets
import pandas as pd

In [2]:
Wine=datasets.load_wine()

In [3]:
x=Wine.data
y=Wine.target
col1=Wine.feature_names
col2=Wine.target_names

In [4]:
df=pd.DataFrame(x,columns=col1)

In [5]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [6]:
def euclidean_distance(row1,row2):
    distance=0.0
    print(len(row1))
    for i in range(len(row1)-1):
        distance+=(row1[i]-row2[i])**2
    return sqrt(distance)

In [7]:
dataset=[[1,2,3],[1.2,2.4,3.2],[2.6,2,3],[1,3,2],[5,4,3],[3,4,5],[6,5,4],[7,4,2]]
row0=dataset[0]
print(row0)
for row in dataset:
    print(row)
    distance=euclidean_distance(row0,row)
    print(distance)

[1, 2, 3]
[1, 2, 3]
3
0.0
[1.2, 2.4, 3.2]
3
0.4472135954999578
[2.6, 2, 3]
3
1.6
[1, 3, 2]
3
1.0
[5, 4, 3]
3
4.47213595499958
[3, 4, 5]
3
2.8284271247461903
[6, 5, 4]
3
5.830951894845301
[7, 4, 2]
3
6.324555320336759

In [8]:
def get_neighbour(train,test_row,num_neighbour):
    distances=list()
    for train_row in train:
        dist=euclidean_distance(test_row,train_row)
        distances.append((train_row,dist))
        distances.sort(key=lambda tup: tup[1])
    neighbours=list()
    for i in range(num_neighbour):
        neighbours.append(distances[i][0])
    return neighbours
#get_neighbour(4,4,2)

In [9]:
dataset=[[1,2,3],[1.2,2.4,3.2],[2.6,2,3],[1,3,2],[5,4,3],[3,4,5],[6,5,4],[7,4,2]]
row0=dataset[0]
print(row0)
neighbours=get_neighbours(dataset,dataset[0],3)
for neighbour in neighbours:
    print(neighbour)

[1, 2, 3]

NameError: name 'get_neighbours' is not defined

In [10]:
def Haming_distance(row1,row2):
    distance=0.0
    print(len(row1))
    for i in range(len(row1)-1):
        ham_distance+=abs((row1[i]-row2[i]))
    return (ham_distance)

In [11]:
dataset=[[1,2,3],[1.2,2.4,3.2],[2.6,2,3],[1,3,2],[5,4,3],[3,4,5],[6,5,4],[7,4,2]]
row0=dataset[0]
print(row0)
for row in dataset:
    print(row)
    ham_distance=Haming_distance(row0,row)
    print(ham_distance)

[1, 2, 3]
[1, 2, 3]
3

UnboundLocalError: cannot access local variable 'ham_distance' where it is not associated with a value

In [12]:
def Manhattan_distance(row1,row2):
    distance=0.0
    print(len(row1))
    for i in range(len(row1)-1):
        man_distance+=m.modf(row1[i]+row2[i])
    return (man_distance)

In [13]:
dataset=[[1,2,3],[1.2,2.4,3.2],[2.6,2,3],[1,3,2],[5,4,3],[3,4,5],[6,5,4],[7,4,2]]
row1=dataset[0]
print(row1)
for row in dataset:
    print(row)
    man_distance=Manhattan_distance(row1,row)
    print(ham_distance)

[1, 2, 3]
[1, 2, 3]
3

UnboundLocalError: cannot access local variable 'man_distance' where it is not associated with a value